name: Build Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: yard1/hoi4_headless
      volumes:
        - "/home/runner/work/hoi4-mod-test/hoi4-mod-test:/home/steam/workspace"
      options: --shm-size 256M --rm
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
        fetch-depth: 1
    - name: Build release through PrepareForUpload.sh
      run: |
        cd /home/steam/workspace
        sudo chmod +x ./PrepareForUpload.sh
        ./PrepareForUpload.sh
        cd ..
        mv hoi4_mod_test mod
        mv hoi4-mod-test.mod mod
        cd mod
        pwd
        zip -r hoi4-mod-test.zip .
        mv hoi4-mod-test.zip /home/steam/workspace
      env:
        STEAM_LOGIN: Equestria_at_War
        STEAM_PASSWORD: ${{ secrets.STEAMPASSWORD }}
        PDX_LOGIN: antoni.baum@protonmail.com
        PDX_PASSWORD: ${{ secrets.PDXPASSWORD }}
        GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLEAPICREDENTIALS }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLECLIENTSECRET }}
        STEAM_SENTRY_FILE_NAME:  ${{ secrets.STEAMSENTRYFILENAME }}
        STEAM_SENTRY_FILE_HEX: ${{ secrets.STEAMSENTRYFILEHEX }}
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: hoi4-mod-test.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
